apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-crds.yaml
  - 02-serviceaccounts.yaml
  - 03-roles.yaml
  - 04-clusterroles.yaml
  - 05-rolebindings.yaml
  - 06-clusterrolebindings.yaml
  - 07-configmaps.yaml
  - 08-secrets.yaml
  - 09-services.yaml
  - 10-deployments.yaml
  - 11-statefulsets.yaml
  - 12-networkpolicies.yaml

